import { TypeLayout } from '@/interfaces/global'


import './globals.css'

export const metadata = {
  title: 'FREE-DELIVERY',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: TypeLayout) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
